#php | Docker Hub公式イメージ
FROM php:8.1-fpm-buster
#コンテナ内のサーバー環境変数
ENV COMPOSER_ALLOW_SUPERUSER=1 \
  COMPOSER_HOME=/composer

COPY --from=composer:2.2 /usr/bin/composer /usr/bin/composer

RUN apt-get update && \
  apt-get -y install --no-install-recommends git unzip libzip-dev libicu-dev libonig-dev && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* && \
  docker-php-ext-install intl pdo_mysql zip bcmath

COPY ./infra/php/php.ini /usr/local/etc/php/php.ini
CMD php artisan serve --host=0.0.0.0 --port $PORT
WORKDIR /data
EXPOSE $PORT
